### ISSUE TITLE
Should not be possible to add ENV if the instance is not present in PP

### ISSUE THREAD

**Issue by ignacy** [mdyd-dev/pos-cli#125]
## Expected behavior 

`marketplace-kit env add staging http//no-such-instance` should return error: "Could not find instance: no-such-instance "

## Actual behavior

As long as the authentication is OK it will not produce an error AND it will add the ENV to configuration file.

## Steps to reproduce the problem

Described above

### Marketplace Kit
All (2.7.X)
### NodeJs
All
### Operating System
All

**Comment by pavelloz** [comment]
@ignacy It looks like Portal just returns token if email/password is correct, so this needs to be handled on PP side first.

**Comment by pavelloz** [comment]
Looks like it has been fixed when introducing tokens per instance
<img width="935" alt="image" src="https://user-images.githubusercontent.com/546845/79452934-3b774080-7fe9-11ea-8b21-60870b3299b3.png">
