### ISSUE TITLE
`migrations run` should upload migration code before running

### ISSUE THREAD

**Issue by ignacy** [mdyd-dev/pos-cli#130]
## Expected behavior 

Not really a bug - more of a feature request: `mk migrations run staging 20191111202020` should upload the code and run (combine sync & run).

## Actual behavior

Run does not upload the code so if the developer does not deploy/sync migration code there is nothing to run.

## Version:

All versions

**Comment by pavelloz** [comment]
Will it work if i did partial deploy of this one migration file?

**Comment by z-x** [comment]
Sync & deploy does this.
