### ISSUE TITLE
marketplace-kit-migrations-run command not found

### ISSUE THREAD

**Issue by jnorbert** [mdyd-dev/pos-cli#167]
## Actual behavior
user:~/qa-migration/marketplace_builder/migrations$ marketplace-kit migrations run staging 20190418133149_new_user.liquid

[15:55:08] No settings for staging environment, please see marketplace-kit env add

Usage: marketplace-kit-migrations-run [options] [environment] <timestamp>

## Expected behavior
Usage: marketplace-kit migrations run [options] [environment] <timestamp>

**Comment by pavelloz** [comment]
Found a way to fix this.

`Usage: pos-cli deploy [options] [environment]`

```
program
  .name('pos-cli deploy')
```
