### ISSUE TITLE
marketplace-kit data import should lock other data commands untill finish.

### ISSUE THREAD

**Issue by piotrze** [mdyd-dev/pos-cli#178]
![image](https://user-images.githubusercontent.com/96238/58408005-375ad100-806d-11e9-8211-b28237709efb.png)

We should include a warning if prior batches are still being processed, so we're no creating a race condition.

**Comment by pavelloz** [comment]
Agree.

IMO mpkit could ask server if anything is pending before any data is sent (just in case data import file is big - huge time savings) - if it is processing (or in queue), it should throw straight away.

**Comment by z-x** [comment]
Moved to Trello
