### ISSUE TITLE
pos-cli start command

### ISSUE THREAD

**Issue by Slashek** [mdyd-dev/pos-cli#191]
Add `pos-cli start <env>` command, which would be equivalent of running `sync`, `gui serve` and `logs` at the same time

**Comment by pavelloz** [comment]
https://github.com/mdyd-dev/todo-app/blob/master/package.json#L3-L10 ;)

**Comment by pavelloz** [comment]
https://documentation.platformos.com/developer-guide/platformos-workflow/effective-development-using-pos-cli
