### ISSUE TITLE
file name validation

### ISSUE THREAD

**Issue by lemingos** [mdyd-dev/pos-cli#197]
## Expected behavior 
File name with `'` like:
`modules/account/public/authorization_policies/can't_delete_seller.liquid`  
should raise validation error

## Actual behavior
possible to sync

## Steps to reproduce the problem
create a file and sync/deploy
## Version:
all

**Comment by pavelloz** [comment]
Can you prepare full list on invalid characters?
I'll compose check in `shouldBeSynced` module.

**Comment by pavelloz** [comment]
- [x] audit warning while deploying
- [ ] throwing error when trying to sync file with invalid name

**Comment by Coornail** [comment]
Should be fixed by #368 .
