### ISSUE TITLE
rename `marketplace-kit` to `pos-cli`

### ISSUE THREAD

**Issue by Slashek** [mdyd-dev/pos-cli#205]

**Comment by pavelloz** [comment]
- [ ] add alias pos-cli in ./bin
- [ ] create new organization in npm `@platformos`
- [ ] move package to `@platformos/pos-cli`
- [ ] rename repo in github to `pos-cli` (?)
- [ ] publish v1.0
- [ ] update messaging in `pos-cli`
- [ ] update docs
- [ ] update messaging in platform (is there any?)

**Comment by pavelloz** [comment]
Done.

**Comment by pavelloz** [comment]
Some notes:
https://www.notion.so/marketplace-kit-pos-cli-7a848e89bbc04016bd5373385fbecd11
