### ISSUE TITLE
Make audit results cached

### ISSUE THREAD

**Issue by pavelloz** [mdyd-dev/pos-cli#242]
Since we are now running audit on every deploy, its time to conserve some energy, save a lot of time for users and save the planet.
One bird two stones. /s

On audit create file with metadata:

```
	filePath,
	result,
	mtime
```

If the file did not change AND was flawless during the last check, do not check the file again.

This should speed up most of our use cases... A LOT.

**Comment by Developer-DNM** [comment]
Love it.

**Comment by pavelloz** [comment]
Putting on hold in favor of https://github.com/mdyd-dev/pos-cli/issues/250

Might not be necessary complexity after this much smaller optimization fix.

credits to @kv109 for idea

**Comment by pavelloz** [comment]
Not needed anymore. ;)
