### ISSUE TITLE
[BUG] partial deploy do not work

### ISSUE THREAD

**Issue by lemingos** [mdyd-dev/pos-cli#244]
## Expected behavior
deploy with -p should work without app directory

## Actual behavior
```
[16:38:21] Deploy failed. Reason: Archive creation.
app can't be empty if the deploy is not partial - it would remove all the files from the instance
```

## Steps to reproduce the problem

Deploy module 
## Version

* pos-cli:
3.0.8
* node:
v10.16.0
* os:
Ubuntu 18.04.2 LTS

**Comment by Slashek** [comment]
Also check if app/modules is a valid path and works for "all" cases
