### ISSUE TITLE
Toplevel `modules` is a valid folder name

### ISSUE THREAD

**Issue by ignacy** [mdyd-dev/pos-cli#249]
## Expected behavior

```
> ls
modules
```

Is a valid directory structure.

## Actual behavior

`PosCli` requires toplevel folder named `app` to be present.

## Steps to reproduce the problem

Try deploying modules with only the modules folder present

## Version

* pos-cli: 3.0.8
* node: all
* os: all

**Comment by Slashek** [comment]
duplicate of #244
