### ISSUE TITLE
Optimize audit regexp implementation

### ISSUE THREAD

**Issue by pavelloz** [mdyd-dev/pos-cli#250]
Dynamically stitch together regexps for filters and tags to avoid running algo 1 time per rule, but 1 time per all rules.

**Comment by pavelloz** [comment]
In the prototype phase by optimizing regexp and going down the stack, bypassing all the abstractions gives around 2100x speed up.

**Comment by pavelloz** [comment]
Before:
```
12.779 total
```

After:
```
0.239 total
```

Im pretty happy with that.

**Comment by Developer-DNM** [comment]
@pavelloz eXtreme Performance !!!
