### ISSUE TITLE
Deployment issue in windows

### ISSUE THREAD

**Issue by chandu-menda** [mdyd-dev/pos-cli#304]
## Expected behavior

![deployment-1](https://user-images.githubusercontent.com/45281783/62947460-2d40a700-be00-11e9-9965-ccad269d2f2c.PNG)

## Version

* pos-cli: 4.1.3
* node: v10.8.0
* os: windows

**Comment by Ben-Probity** [comment]
I'm also having the same issue with deploying on my windows machine
![spawnUNKNOWN](https://user-images.githubusercontent.com/34144939/63404653-617f1d80-c427-11e9-930a-2d3f9e031026.jpg)
**VERSION**

- node: v10.16.3
- pos-cli: v4.1.7
- windows: v1903

**Comment by Ben-Probity** [comment]
Hey @Slashek, unfortunately even after updating to the latest version (currently 4.1.8) I'm still experiencing the same issue.

**Comment by Developer-DNM** [comment]
@Ben-Probity  Can you look if either of the Bash options for Windows 10 might temporarily solve the problem: https://itsfoss.com/install-bash-on-windows/  

We're having issues with more recent Win 10 updates and whatever quirks they've introduced.
We want to fix this right within our CLI and not have to worry about a 3rd part dependency.

Thanks for helping as work this one out together.
(Working with Windows CLI is like trying to program around IE6 non-standards.  Thankfully it seems MS are now moving into modern code standards and going to support the Linux kernel - great news)

**Comment by Ben-Probity** [comment]
Hey @Developer-DNM, I have followed the directions in the link provided and have installed ubuntu app and created my unix name and PW. The problem that I am having now is that when I install nodejs: "sudo apt-get install nodejs" through ubuntu as it returns: 
"Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nodejs"
I then tried "sudo apt-get install build-essential" in the hopes that it would download the necessary things I need but this also failed and showed a lot of errors in the installation. --fix-missing and update also don't work to get the failed files (Didn't think it would).

I have also tried following this to a "T": https://www.windowscentral.com/how-install-bash-shell-command-line-windows-10 
However, when I go to open bash.exe it flashes up then immediately closes.

**Comment by Developer-DNM** [comment]
Sorry @Ben-Probity Windows 10 is really being problematic, if bash isn't even loading for you sounds like a deeper Win 10 environment issue.

We might have to do a screenshare.
I've been a PC/DOS/Windows user since the XT and DOS 1.0, but seriously frustrated with getting an easy Windows Dev environment setup for modern standards.

We'll keep trying to see how we can reproduce on our PC machines.
If you have a Mac handy, that'll work for sure in the meantime.

**Comment by Slashek** [comment]
@Ben-Probity does this help - http://pjdecarlo.com/2016/06/bash-on-windows-as-integrated-terminal-in-visual-studio-code.html ?

**Comment by Ben-Probity** [comment]
Thats alright @Developer-DNM typical windows by the sounds of it... As for having a mac, it isn't feasible as we only use PC's at work.

Hey @Slashek - unfortunately, that isn't working either.

**Comment by piotrze** [comment]
@Ben-Probity We have released 4.1.10 with fixes for windows.
