### ISSUE TITLE
Does not show list of valid page types

### ISSUE THREAD

**Issue by ignacy** [mdyd-dev/pos-cli#308]
I was creating a page with `method: POST` which is invalid (should be valid probably) because it has to be lowercase `post` but the error message does not show the list of valid methods correctly:

<img width="605" alt="Zrzut ekranu 2019-08-19 18 42 06" src="https://user-images.githubusercontent.com/25693/63283312-2fe44600-c2b1-11e9-83f0-86812aa12b22.png">

**Comment by Developer-DNM** [comment]
Another example of why it's great having the core team working on real-world projects, so that we can see what other's are going to experience and rectify.

Thanks again @ignacy 👍

**Comment by pavelloz** [comment]
Fixed 
<img width="874" alt="image" src="https://user-images.githubusercontent.com/546845/71166072-3defa680-2252-11ea-91d0-48ac15a90eff.png">
