### ISSUE TITLE
Deploy command no longer recognised in 4.1.12 ?

### ISSUE THREAD

**Issue by MattJonesSiteglide** [mdyd-dev/pos-cli#321]
## Expected behavior
pos-cli deploy UAT runs a deploy to UAT environment

## Actual behavior
Error message [10:42:28] unknown command: deploy

## Steps to reproduce the problem
I deployed fine, then updated to latest version of pos-cli. Afterwards it no longer recognised the command. 

## Version

* pos-cli: 4.1.12
* node: v10.16.0
* os: Windows 10

**Comment by piotrze** [comment]
@MattJonesSiteglide It has been fixed in 4.1.14
