### ISSUE TITLE
Couldn't find FormConfiguration for 'assets/scripts/script.js'

### ISSUE THREAD

**Issue by jnorbert** [mdyd-dev/pos-cli#371]
## Expected behavior
[Sync] Deleted: assets/scripts/script.js

## Actual behavior
Couldn't find FormConfiguration for 'assets/scripts/script.js'
assets/scripts/script.js

<img width="953" alt="Screenshot 2020-03-24 at 14 00 07" src="https://user-images.githubusercontent.com/13810654/77428076-cc3a7200-6dd7-11ea-9d38-ff915ef2fac9.png">

## Steps to reproduce the problem
1. pos-cli init
2. Create two files with some code in app/assets/scripts, for example, script.js & script_copy.js
3. pos-cli sync staging
4. Remove script.js file

## Version

* pos-cli: 4.4.4
* node: 10.16.3
* os: MAC OS X

**Comment by pavelloz** [comment]
BTW. This has nothing to do with pos-cli - this is our new server-side validations :)

**Comment by pavelloz** [comment]
@Slashek this is fixed right?

**Comment by Slashek** [comment]
yes, it was hardcoded error message which we were displaying when trying to delete resource which had been already deleted. Now we will correctly display resource name
