### ISSUE TITLE
sync only works for the first couple file saves

### ISSUE THREAD

**Issue by onecreative** [mdyd-dev/pos-cli#376]
## Expected behavior
sync every save/delete

## Actual behavior
Syncs the first couple of times, but has to be restarted to make it work after that.

## Version

* pos-cli: 4.4.6
* node: 10.15.1
* os: MacOS 10.15.3

**Comment by onecreative** [comment]
It appears it is always three times.

**Comment by pavelloz** [comment]
Published 4.4.7 - should be fixed. Fix is amazing, highly recommended lecture.
