### ISSUE TITLE
gui serve - uuid/v4 deprecation warning

### ISSUE THREAD

**Issue by mattwalter91** [mdyd-dev/pos-cli#411]
Seeing a deprecation warning in terminal logs ->

(node:19640) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.

## Steps to reproduce the problem
`pos-cli gui serve <env>`

## Version

* pos-cli: 4.4.13
* node: 12.16.2
* os: Windows 10

**Comment by pavelloz** [comment]
Fixed on march 15 - https://github.com/mdyd-dev/pos-cli/commit/42b5cc7e5e7d97db1153d5f1ae444dd56d9660b0
