### ISSUE TITLE
[npmjs] Some of the links redirect to the outdated pages

### ISSUE THREAD

**Issue by jnorbert** [mdyd-dev/pos-cli#412]
## URL
https://www.npmjs.com/package/@platformos/pos-cli

## Actual behavior
<img width="2558" alt="Screenshot 2020-06-15 at 16 03 20" src="https://user-images.githubusercontent.com/13810654/84666795-d1fcab00-af21-11ea-8c1b-8f1463b4e3bb.png">

**Comment by pavelloz** [comment]
Fixed
