### ISSUE TITLE
Blank graphql fails validation with misleading error message

### ISSUE THREAD

**Issue by richxrich** [mdyd-dev/pos-cli#439]
## Expected behavior
An error message more representative of the issue:
[ time ] Validation failed: Graphql files can't be blank
modules/....

## Actual behavior
[time] Validation failed: Query string can't be blank
modules/....

## Steps to reproduce the problem
Deploy something with a blank graphql file

## Version

* pos-cli: 4.4.24
* node: 10.16.3
* os: Windows 10

**Comment by z-x** [comment]
![image](https://github.com/mdyd-dev/pos-cli/assets/1907443/0bd1552f-1962-404f-97a8-82145f3f9edb)

**Comment by piotrze** [comment]
Fixed 
![image](https://github.com/mdyd-dev/pos-cli/assets/96238/6c863e61-46e6-4598-8577-8708044634e4)
