### ISSUE TITLE
Liquid block comment validation failure

### ISSUE THREAD

**Issue by richxrich** [mdyd-dev/pos-cli#441]
## Expected behavior
To pass validation

## Actual behavior
Does not pass validation

## Steps to reproduce the problem
Sample code:
```
{% liquid
	comment
		if I will fail because I start with an "if" with "Validation failed: Body syntax is invalid (Liquid syntax error: Expected end_of_string but found id in...."
	endcomment
%}
```

## Version

* pos-cli: whatever the latest is (sorry!)
* node:
* os:

**Comment by pavelloz** [comment]
pos-cli is just sending data, server is responding with liquid error. Cant do anything here.

**Comment by z-x** [comment]
Liquid internal issue.
