### ISSUE TITLE
Environment with trailing slash results in graphqli not working due to redirects

### ISSUE THREAD

**Issue by chrisdanek** [mdyd-dev/pos-cli#442]
## Expected behavior

Add a new environment on production with a trailing slash in the URL `https://example.com/` should work the same way when no trailing slash is added `https://example.com`

## Actual behavior

When adding a trailing slash I am unable to use `pos-cli gui` tools

## Steps to reproduce the problem

1. Add a new environment with trailing slash. *Important note* this does not seem to affect staging domains, only a custom domain on production. 
2. When enabling Grapqhli tool I will get

```json
{
  "statusCode": 301,
  "body": "Moved Permanently",
  "headers": {
    "date": "Mon, 23 Nov 2020 16:52:01 GMT",
    "transfer-encoding": "chunked",
    "connection": "keep-alive",
    "server": "openresty",
    "location": "https://www.example.com//api/graph",
    "x-request-id": "f959f847-c358-4da7-b7ba-064976c425cf",
    "x-runtime": "0.007294",
    "x-ua-compatible": "IE=edge",
    "x-powered-by": "PlatformOS"
  },
  "request": {
    "uri": {
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "example.com",
      "port": 443,
      "hostname": "example.com",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "//api/graph",
      "path": "//api/graph",
      "href": "https://example.com//api/graph"
    },
    "method": "POST",
    "headers": {
      "Authorization": "Token ...",
      "InstanceDomain": "https://example.com/",
      "User-Agent": "pos-cli/4.4.24",
      "From": "chrisd@near-me.com",
      "accept": "application/json",
      "content-type": "application/json",
      "content-length": 1758
    }
  }
}
```

After further testing and prompt from @godot, I found the problem might be related to `www.` redirect, but funnily enough using `https://example.com` will work just fine. I would expect it to fail the same way.

## Version

* pos-cli: 4.4.24

**Comment by z-x** [comment]
Done
