### ISSUE TITLE
YAML keys are not removed when using pos-cli sync

### ISSUE THREAD

**Issue by z-x** [mdyd-dev/pos-cli#451]
Based on my experience with the Marketplace MVP Template the keys that were removed are not updated when using `sync` and when an .yml file is edited the old keys are still visible on the page.

## Steps to reproduce the problem
1. Run `pos-cli sync` or `npm run start` if you are using the Marketplace MVP Template
2. Edit the an `.yml` file, the `en.yml` if you are using the Marketplace MVP Template
3. Use any view to render a key on the page, preferably a key that has child nodes
4. Remove any of this child nodes and let it sync to the page
5. Refresh the page, the child node will still be visible

## Version

* pos-cli: 4.4.26
* node: 12.19.0
* os: Win 10 Home 10.0.19042 Build 19042

**Comment by andrew-3** [comment]
Created internal PR: #10159

**Comment by z-x** [comment]
Escalated.
