### ISSUE TITLE
No assets in modules/ release?

### ISSUE THREAD

**Issue by pavelloz** [mdyd-dev/pos-cli#472]
`pos-cli deploy` command.

File tree:
<img width="188" alt="image" src="https://user-images.githubusercontent.com/546845/135057320-cd67c036-e4cd-4de6-8c1a-07ae0b5b94e8.png">

Vs release.zip contents:
<img width="274" alt="image" src="https://user-images.githubusercontent.com/546845/135057401-7f37c4ad-73d6-4028-a788-ff80278e83a9.png">

I think assets should be included if no --without-assets are specified.

**Comment by piotrze** [comment]
It works. In deploy we use direct asset upload this is why we don't have js files in `release.zip`. They are uploaded and you can fetch the content
