### ISSUE TITLE
New instance admin refreshing pages returns 404

### ISSUE THREAD

**Issue by DomicaCode** [mdyd-dev/pos-cli#504]
## Expected behavior
Refreshing /users, /logs, /constants, /database should refresh the page without any errors.

## Actual behavior
Refreshing throws "Cannot GET /logs" 404 for example

## Steps to reproduce the problem
Go to http://localhost:3334/logs and refresh the page

## Version

* pos-cli: 4.9.1 
* node: v16.16.0
* os: Windows 10

**Comment by z-x** [comment]
Thanks for the info, it seems I've fixed that once and then forgot to test it out in the actual pos-cli implementation. Should be improved with the next pos-cli version shipped early next week.

**Comment by z-x** [comment]
Fixed.
